### ISSUE TITLE
New URLs for Baltimore micromobility

### ISSUE THREAD

**Issue by oonuttlet** [ds-civic-data/bikeshare-1#8]
In `get_gbfs_cities()`, a search for `"Baltimore"` returns 4 `System ID`s of `Link_Baltimore`, `lime_baltimore`, `Link_Alexandria`, and `spin baltimore` with outdated URLs -- these should be (as far as I can tell) updated to:

`bird_baltimore` = https://mds.bird.co/gbfs/v2/public/baltimore/gbfs.json
`link_baltimore` = https://mds.linkyour.city/gbfs/us_md_baltimore/gbfs.json
`spin_baltimore` = https://gbfs.spin.pm/api/gbfs/v2_3/baltimore/gbfs.json

This reflects Baltimore's non-renewal of the contract with Lime, and the new contract with Bird.

**Comment by simonpcouch** [comment]
Ah, thank you for the issue!

This is a package that provides an R interface to [MobilityData/gbfs](https://github.com/MobilityData/gbfs). Those folks maintain a [csv with up-to-date information](https://raw.githubusercontent.com/MobilityData/gbfs/master/systems.csv) about micromobility systems that this package just pings, so the change in metadata will need to happen there. Their [`systems.csv` issue label](https://github.com/MobilityData/gbfs/issues?q=is%3Aissue+label%3Asystems.csv) contains some templates of how other people have reported outages/need for URL changes. :)

**Comment by oonuttlet** [comment]
Simon,

Thanks so much for the help! Much appreciated. I'll go check in over there, too.

Thanks again!
Harrison
